### ISSUE TITLE
Failed to flash bios

### ISSUE THREAD

**Issue by 4Hani** [ryanrudolfoba/SteamDeck-BIOS-Manager#4]
When selecting the different bios versions in the flash window, the program doesn't list the version numbers.
Every file just reads "BIOS" in the program, even though the files are properly named on the system.
So, at the end, it fails with the error: Open file failed. (path="/home/deck/bios/SteamDeck-BIOS-Manager/BIOS/BIOS")

**Comment by 4Hani** [comment]
Update, I redownloaded the BIOS Manager and did the whole thing again, now it showed the actual filenames in the program and it worked just fine.

**Comment by ryanrudolfoba** [comment]
> Open file failed. (path="/home/deck/bios/SteamDeck-BIOS-Manager/BIOS/BIO

Yes because on your fist attempt, it looks like you moved the script to somewhere else, based from the error here -
`Open file failed. (path="/home/deck/bios/SteamDeck-BIOS-Manager/BIOS/BIOS")`

the script on the initial release its hardcoded it looks for the BIOS file in a specific directory. for enhancement i can use variables so it can be run from any folder.
